### ISSUE TITLE
Not compatible with multiple entrypoints in parcel

### ISSUE THREAD

**Issue by BrianRosamilia** [tiaanduplessis/parcel-plugin-asset-copier#8]
Hi,

Love the plugin, but one minor issue

The plugin doesn't support parcel's feature of multiple entrypoints.  

You can use parcel like this (which surprisingly no one else has tried with your plugin)

`parcel index.html index_debug.html --open`

Which changes the shape of what gets passed to your bundle plugin.  The tl;dr is that you need to check for a child bundle as I'm doing on the first line here: 

```
  if(bundler.mainBundle.childBundles.values().next().value){
          bundle = bundler.mainBundle.childBundles.values().next().value;
          pkg = await bundler.mainBundle.childBundles.values().next().value.entryAsset.getPackage();
        }
```

Since your plugin is only working with a single directory copy, you can fix the problem by setting the bundle + package to just be the first bundle (lines 2 + 3)

I can fix this issue with a PR (+ test?) if you want.  Just curious if you would accept it.  Let me know

**Comment by tiaanduplessis** [comment]
Hi @BrianRosamilia! Thank you for opening up the issue. I'll be happy to accept any PR for supporting multiple entry points. Otherwise, I'll get to it ASAP.
